name: Pre-Release JAR

on:
  push:
    branches: [ "prerelease" ]

jobs:
  build-and-release:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the JAR file
        run: mvn clean compile assembly:single

      - name: Extract app version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: SlimTrade ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          prerelease: true
          bodyFile: src/main/resources/patch_notes/v${{ env.VERSION }}.txt
#          bodyFile: src/main/resources/patch_notes/static.txv${{ env.VERSION }}.txtt
          artifacts: target/SlimTrade.jar
          token: ${{ secrets.GITHUB_TOKEN }}